# Conclusion

The results of this study are somewhat in line with what has been documented for the American stock market and the German stock market, by [@chabi2017crash] and [@supper2020comparison], respectively, though slightly less unambiguous. There appears to be a risk premium for investing in stocks that exhibit a high tendency to perform especially poorly when the market crashes. Sorting stocks into quintiles based on their estimated LTD and calculating average one-month-ahead returns, we find a near monotonic increase in value-weighted portfolio returns as a function of LTD quintile. Further, there is a positive difference between the returns of portfolios of stocks that exhibit strong LTD and stocks that exhibit weak LTD, though this difference is neither statistically significant nor of a notable economic magnitude. The results are less clear when we analyse the data by sorting first on different variables and then on LTD. Turning to a multivariate analysis, we find both an economically and statistically significant association between one-month-ahead returns and LTD. This association is stable across all our regression specifications. Further, our results are robust to different portfolio formations when performing portfolio sorts analyses and to different copula selection criteria in the regression analyses.  