# Introduction

## Idea

This paper is based on the following assumption about investor preferences. Investors dislike crash risk. More specifically, investors are willing to pay more for assets that do not perform poorly in bad times. Another way to look at this is that investors demand a risk premium for holding assets which perform poorly in bad times. This makes intuitive sense. Under standard assumptions we know that investors have higher marginal utility during bad times than during good times. It follows that assets that perform well during bad times are worth more to investors than assets that perform poorly during bad times. A textbook exposition of these assumptions can be found in [@GVK322224764]. Motivated by such reasoning, [@chabi2017crash] studied the presence of a risk premium in American stocks with exposure to crash risk. The crash risk measure they used will be formally defined later in this article. Informally, they defined the crash risk of a stock as the conditional probability of a very low return given a very low market return. They indeed found a robust positive association between stock crash risk exposure and stock returns. Additionally, [@chabi2017crash] showed that under fairly general assumptions, such a relationship is predicted by standard asset pricing theoretical frameworks. 

Motivated by the above, I want to study Nordic stock markets and whether a crash risk premium exists. I have chosen to look at four broad stock indices from Norway, Sweden, Denmark and Finland. I wish to consider the Nordic stock markets as one entity, i.e., to treat all the Nordic stock markets as one big market, for several reasons. Firstly, looking at for example the Norwegian stock market in isolation, one runs the risk of results not being generalizable due to the composition of the index. This is because the Norwegian stock market is heavily dominated by companies in certain sectors, for example the energy sector. A second reason for considering the Nordic stock market as one entity is statistical, namely the sample size. Thirdly, even though the different markets in the Nordic countries are different, the societies are still quite similar. The third reason is not formally testable, but it shall simply be assumed that there is enough commonality between the abovementioned stock markets that it makes sense to consider them as one entity. 

## Related Literature

It has been documented in many papers, for example in [@longin2001extreme], that equity correlations increase during market downturns. Not only that, the degree to which they increase is markedly higher than during market upturns. This is echoed by [@stove2014asymmetric], where a different measure of dependence is used. Other notable papers investigating asymmetries in the distribution of financial returns are [@silvapulle2001large], [@okimoto2008new], [@ang2002asymmetric], [@hong2007asymmetries], [@chollete2009modeling] and [@garcia2011dependence]. Either implicitly or explicitly, these studies also document that financial returns are not Gaussian. This implies that (Pearson) correlation is no longer a complete measure of the dependence in financial returns. [@embrechts2002correlation] gives an overview of properties and pitfalls of correlation as a measure of dependence. 

The documented asymmetries above suggests that diversification benefits are present to a lesser extent during market downturns than otherwise. This has implications for investors that are averse to crash risk. If investors are averse to crashes, a large drop in their wealth implies a disproportionately large drop in utility. As such, it is natural to consider a measure of crash risk that considers market downturns. [@chabi2017crash] provides a theoretical motivation for why such a measure of crash risk, which we will define in more detail later, is priced in a stochastic discount factor framework. Further, they analyze empirically whether exposure to crash risk is associated with higher expected stock returns. They find that stocks with low crash risk serve as a hedge during crises and that stocks with high crash risk have higher average future returns. 

[@agarwal2017tail] conducts a similar empirical study, where they consider equity oriented hedge fund returns rather than stock returns. They find that crash risk affects the cross-sectional variation in fund returns. Both studies find that exposure to crash risk is associated with higher expected returns.  It should be mentioned that, though the two studies partly use the same measure of crash risk, they estimate this measure differently. [@karagiannis2019tail] find that crash risk helps to explain cross-sectional variation in mutual fund returns. They employ the Hill estimator from [@hill1975simple] to estimate a measure of tail risk developed by [@kelly2014tail]. This is an unconditional measure of crash risk, and as such it differs from the measures used in [@chabi2017crash] and [@agarwal2017tail], which measures crash risk conditional on a market crash. [@kelly2014tail] themselves investigate tail risk and asset prices and find that cross-sectionally, stocks with high loadings on past tail risk earn an annual three-factor alpha 5.4 % higher than stocks with low tail risk loadings. 

Related work has been done with other risk measures. One of them is downside risk, which separates itself from crash risk by not restricting its attention far out in the tails of the relevant probability distributions. [@ang2006downside] find that the cross section of stock returns reflects a downside risk premium of approximately 6 % per annum. Stocks that covary strongly with the market during market declines have high average returns. [@yan2011jump] uses option data to investigate how the expected return of a stock is dependent on what he refers to as jump risk and how jump risk can be measured. 

There are several alternative measures of crash risk in the literature. One such measure is conditional correlation, i.e. the correlation between two return series conditioned on one of the return series being below a certain threshold. It is noted in [@ang2002asymmetric] that calculating correlations conditional on high or low returns induces a conditioning bias in the correlation estimates. This was also noted earlier by [@boyer1999pitfalls]. Furthermore, it is well known that correlation as a measure of dependence is sensitive to large realizations of the random variables in question. Therefore, one might expect that conditional correlation is not a very good empirical measure of dependence in the tails of a probability distribution as the conditioning might leave few observations, some of which might be very large in magnitude. 

<!-- \subsection{Literature specific to Nordic countries} -->

<!-- Fill in literature here.  -->